import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import  PDFDocument from 'pdfkit';

import { Invoice } from './entities/invoice.entity';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { UpdateInvoiceDto } from './dto/update-invoice.dto';

@Injectable()
export class InvoicesService {
  constructor(
    @InjectRepository(Invoice)
    private invoiceRepository: Repository<Invoice>,
  ) {}

  create(createInvoiceDto: CreateInvoiceDto) {
    const invoice = this.invoiceRepository.create(createInvoiceDto);
    return this.invoiceRepository.save(invoice);
  }

  findAll() {
    return this.invoiceRepository.find();
  }

  findOne(id: number) {
    return this.invoiceRepository.findOne({
      where: { id },
    });
  }

  async update(id: number, updateInvoiceDto: UpdateInvoiceDto) {
    await this.invoiceRepository.update(id, updateInvoiceDto);
    return this.findOne(id);
  }

  async remove(id: number) {
    const invoice = await this.findOne(id);

    if (invoice) {
      await this.invoiceRepository.delete(id);
    }

    return {
      message: 'Invoice deleted successfully',
    };
  }

  async generatePdf(id: number) {
    const invoice = await this.findOne(id);

    if (!invoice) {
      throw new Error('Invoice not found');
    }

    const doc = new PDFDocument();

    const buffers: Buffer[] = [];

    doc.on('data', (chunk) => buffers.push(chunk));

    return new Promise<Buffer>((resolve) => {
      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });

      doc.fontSize(22).text('INVOICE', {
        align: 'center',
      });

      doc.moveDown();

      doc.fontSize(14).text(`Invoice ID: ${invoice.id}`);
      doc.text(`Customer ID: ${invoice.customerId}`);
      doc.text(`Product ID: ${invoice.productId}`);
      doc.text(`Quantity: ${invoice.quantity}`);
      doc.text(`Total Amount: ₹${invoice.totalAmount}`);
      doc.text(`Invoice Date: ${invoice.invoiceDate}`);

      doc.moveDown();

      doc.text('Generated by SaaS Billing System');

      doc.end();
    });
  }
}